services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: ./
      dockerfile: DockerFiles/dockerfile
    container_name: web
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  postgres_data: